schema_version: 1

context:
  version: "2021.0814"

package:
  name: perl-text-tabs-wrap
  version: ${{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/A/AR/ARISTOTLE/Text-Tabs+Wrap-${{ version }}.tar.gz
  sha256: 30bbea13a5f5ef446b676b4493644df0ea19fc6a70ff649a8beb64571dbf6dfa

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

tests:
  - perl:
      uses:
        - Text::Tabs
        - Text::Wrap

about:
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  summary: Expand tabs and do simple line wrapping
  license_file:
    - ${{ PREFIX }}/man/man1/perlartistic.1
    - ${{ PREFIX }}/man/man1/perlgpl.1
  homepage: https://metacpan.org/dist/Text-Tabs+Wrap

extra:
  recipe-maintainers:
    - cbrueffer
